# Generated by Django 6.0.3 on 2026-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location_text',
        ),
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='balconies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='building_structure',
            field=models.CharField(blank=True, choices=[('beton', 'Beton'), ('caramida', 'Cărămidă'), ('bca', 'BCA'), ('lemn', 'Lemn')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='building_type',
            field=models.CharField(blank=True, choices=[('bloc', 'Bloc de apartamente'), ('casa', 'Casă/Vilă')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='comfort_level',
            field=models.CharField(blank=True, choices=[('1', 'Confort 1'), ('2', 'Confort 2'), ('3', 'Confort 3'), ('lux', 'Lux')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='data_completeness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A', 'Clasa A'), ('B', 'Clasa B'), ('C', 'Clasa C'), ('D', 'Clasa D'), ('E', 'Clasa E'), ('F', 'Clasa F'), ('G', 'Clasa G')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='entrance_door',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='flooring',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnishing_state',
            field=models.CharField(blank=True, choices=[('mobilat', 'Mobilat (Complet)'), ('partial', 'Parțial mobilat'), ('nemobilat', 'Nemobilat')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_dishwasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_gas_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_heat_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_hood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_intercom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_oven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_sewage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_underfloor_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_video_surveillance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_water_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('centrala_proprie', 'Centrală proprie'), ('centrala_imobil', 'Centrală imobil/bloc'), ('termoficare', 'Termoficare (Radet)'), ('incalzire_electrica', 'Încălzire electrică'), ('calorifere', 'Calorifere')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='interior_doors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchens',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='near_public_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('decomandat', 'Decomandat'), ('semidecomandat', 'Semidecomandat'), ('nedecomandat', 'Nedecomandat'), ('circular', 'Circular')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Așteaptă curățare'), ('PROCESSED', 'Curățat'), ('ERROR', 'Eroare')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_website',
            field=models.CharField(default='Necunoscut', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_lit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_paved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='thermal_insulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='useful_surface',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='walls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='windows',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_model_version',
            field=models.CharField(blank=True, help_text='Ex: gpt-4-turbo-2024-04-09', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='token_usage',
            field=models.IntegerField(default=0, help_text='Numărul total de tokeni consumați pentru acest raport'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
