# Generated by Django 6.0.3 on 2026-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_listing_location_text_listing_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='price_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
