# Generated by Django 6.0.3 on 2026-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_price_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='has_ac',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_dishwasher',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_electricity',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_elevator',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_fridge',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_gas',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_gas_meter',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_heat_meter',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_hood',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_intercom',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_microwave',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_oven',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_parking',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_sewage',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_tv',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_underfloor_heating',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_video_surveillance',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_washing_machine',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_water',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_water_meter',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_pet_friendly',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='near_public_transit',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street_lit',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street_paved',
            field=models.BooleanField(blank=True, choices=[(True, 'Da (Are)'), (False, 'Nu (Nu are)'), (None, 'Nemenționat (NULL)')], default=None, null=True),
        ),
    ]
