# Generated by Django 6.0.3 on 2026-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listing_has_ac_alter_listing_has_dishwasher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='distance_verification',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
