# Generated by Django 6.0.3 on 2026-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_report_distance_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitudine extrasă din sursă', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitudine extrasă din sursă', null=True),
        ),
    ]
